# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# rust-clippy is a tool that runs a bunch of lints to catch common
# mistakes in your Rust code and help improve your Rust code.
# More details at https://github.com/rust-lang/rust-clippy
# and https://rust-lang.github.io/rust-clippy/

name: "Code analysis with `clippy` and `fmt`"

on:
  # push:
  #   paths:
  #     - '**.rs'
  #     - Cargo.toml
  #     - Cargo.lock
  #     - .github/workflows/analyze.yml
  #     - 'rust-toolchain.toml'
  pull_request:
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/analyze.yml
      - 'rust-toolchain.toml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  rust-clippy-analyze:
    name: Analyze files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Cargo fmt
        run: cargo fmt --all --check

      - name: Install required tooling for clippy
        run: cargo install clippy-sarif sarif-fmt

      - name: Run `clippy`
        run:
          cargo clippy
          --all-features
          --all-targets
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
